FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv
ENV UV_PYTHON=3.12

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY ./app ./app

# Run the Celery worker
# -c 2 sets the concurrency to 2 processes (adjust based on RAM limits)
CMD sh -c "uv run celery -A app.core.celery_app.celery_app worker --loglevel=info -c 2"