FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

ENV UV_PYTHON=3.11

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY ./app ./app
COPY main.py .

EXPOSE 8000

CMD ["uv", "run", "granian", "--interface", "asgi", "main:app", "--host", "0.0.0.0", "--port", "${PORT:-8000}", "--workers", "4"]