[project]
name = "vm-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beanie>=1.26.0",
    "cloudinary>=1.44.2",
    "fastapi>=0.136.1",
    "granian>=2.7.4",
    "httpx>=0.28.1",
    "huggingface-hub>=1.16.1",
    "motor>=3.6.0",
    "orjson>=3.11.9",
    "passlib[bcrypt]>=1.7.4",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "structlog>=25.5.0",
    "tenacity>=9.0.0",
    "uvicorn>=0.47.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]
